services:
  - type: web
    name: navalha-frontend
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: NEXT_PUBLIC_USAR_MOCKS
        value: "false"
